### ISSUE TITLE
It's time to switch to gitee.com/gofrs/uuid

### ISSUE THREAD

**Issue by FlyingOnion** [satori/go.uuid#118]
This gofrs has nothing to do with github.com/gofrs. I just want to urge them to support go module asap.

Package main page: https://pkg.go.dev/gitee.com/gofrs/uuid/v4

For Chinese friends suffering from poor network when connecting to GitHub, it's time.

**Comment by cameracker** [comment]
Hi, gomod support was added to `gofrs/uuid` Feburary last year. https://github.com/gofrs/uuid/pull/116
