### ISSUE TITLE
Implement json.Marshaler/Unmarshaler

### ISSUE THREAD

**Issue by EricLagergren** [satori/go.uuid#15]
I'd be useful and easy to implement the json.Marshaler/Unmarshaler interfaces just like the binary.BinaryMarshaler/BinaryUnmarshaler interfaces are.

I'll submit a PR if this sounds reasonable.

**Comment by satori** [comment]
As far as I know `encoding.json` package checks for `encoding.TextMarshaler` and `encoding.TextUnmarshaler` interfaces which are implemented by `go.uuid`.
See https://golang.org/pkg/encoding/

**Comment by EricLagergren** [comment]
Yeah it does, my bad.
