### ISSUE TITLE
API should return entropy errors

### ISSUE THREAD

**Issue by satori** [satori/go.uuid#18]
There is an issue with current library API, which doesn't allow library users to gracefully handle entropy errors. This problem was on my mind for some time, but looks like other people have concerns about it as well:
- cloudfoundry/cf-smoke-tests#13

By the time `safeRandom()` has been introduced in #12, v1/v2 storage initialisation had been done inside `init` function, so it looked quite reasonable to `panic` there as it was the only way to handle errors during `init`.
But nothing is eternal and #13 moved v1/v2 storage initialisation out of `init` to make v3/v5 UUID generation possible without any entropy.

Although entropy failure occurs only in some rare and exotic cases, there is no really good reason to hide `error` or `panic` in library internals.
In the same time library became surprisingly popular across the community and it is not the best decision to suddenly break the current API without giving a time to adopt a new one.

So I would like to introduce a **deprecation policy for current library API**.

Unfortunately Go doesn't have a function overloading, and smooth deprecation of an old function signature leads to a new function name.

New API methods which would return `(UUID, error)` will be added and for next 6-12 months old API methods will emit the following warning messages via `log.Printf`:

```
uuid: uuid.NewV1() has been deprecated, use uuid.V1() instead.
uuid: See https://github.com/satori/go.uuid/issues/18 for more info.
```

After a reasonable amount of time (like 6-12 months, mentioned above), I will remove old API methods.

Thanks @m0sth8 for pointing me on that issue and suggesting a deprecation policy.

**Comment by srenatus** [comment]
@satori Hey there 😃 I'm curious, is this being worked on?

**Comment by ivucica** [comment]
FWIW this issue talks about introducing deprecation warnings. But, I don't think I've seen any warnings, nor do I see them removed in https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c.

Was this intended? Did you mean to introduce them first?

This broke at least `gopkg.in/oauth2.v3`.

**Comment by thepauleh** [comment]
+1 invuca, change broke the internet
