### ISSUE TITLE
please tag formal releases

### ISSUE THREAD

**Issue by onlyjob** [satori/go.uuid#22]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also

 * https://en.wikipedia.org/wiki/Software_versioning
 * http://semver.org/

**Comment by satori** [comment]
Done.

**Comment by onlyjob** [comment]
Thank you! :)
