### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by petercolberg** [satori/go.uuid#24]
Please use semantic versioning:

- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by petercolberg** [comment]
Debian packages each Go package repository as a separate Debian source package. In this case, your package has been [included in Debian](https://packages.debian.org/sid/golang-github-satori-go.uuid-dev) as a dependency of [acmetool](https://github.com/hlandau/acme). The version of a Debian package includes an upstream part (e.g. "1.0.0") and a Debian part (e.g. "-1"). If an upstream author does not tag releases, we need to make up an upstream version number based on the git commit and date, which yields unwieldy versions that are cumbersome to compare. 

All you would have to do is regularly tag releases, which yields handy Debian package versions and makes it easy to automatically [notice new upstream releases](https://tracker.debian.org/pkg/golang-gopkg-tylerb-graceful.v1) using the Debian package tracker.

**Comment by satori** [comment]
Done.
