### ISSUE TITLE
Invalid version error

### ISSUE THREAD

**Issue by Iyer-VivekAnand** [satori/go.uuid#28]
I have a set of uuid's which were generated from different platforms and are very old, are now breaking after the recent commits 90e70752a64cf46564d9eede418fe822948f7529.

One such Id which I am using is : ba60a9fc-b22c-9d4c-970e-5fb8eacdbe16
I get "invalid version" when used with FromString.

**Comment by redmoxie** [comment]
Getting the same issue here with GUIDs from Active Directory.

**Comment by satori** [comment]
It should be fixed by 0aa62d5ddceb50dbcb909d790b5345affd3669b6. Thanks for reporting it!
