### ISSUE TITLE
json marshaling

### ISSUE THREAD

**Issue by jeffrom** [satori/go.uuid#29]
with UUID, marshalling to json looks like `{id: "f4ee338d-d66d-452f-93d5-440fa3ae980b"}`, however a NullUUID looks like `id: {
UUID: "3bdef553-9b6a-4620-8a5f-b94bf22a2520",
Valid: true
},`.

Is that your intent? If not I have a pull request that brings NullUUID in line with UUID by implementing encoding.TextMarshaller. Thanks.

**Comment by satori** [comment]
`NullUUID` is not supposed to be used outside of a SQL context. See discussion in #23.

I believe the same is true for `Null*` types from [`sql` package] [1]

[1]: https://golang.org/pkg/database/sql/
