### ISSUE TITLE
Get time from a UUID

### ISSUE THREAD

**Issue by gianarb** [satori/go.uuid#30]
Hello just a question
There is a way, and do this library provide a method to obtain the time from a UUID?
Thanks a lot

**Comment by satori** [comment]
There is no such method as UUID isn't always based on timestamp.

For timestamp-based UUID actual timestamp part is being modified to store UUID version bits, so there is no way to get original time from UUID.

**Comment by gianarb** [comment]
thanks!

**Comment by rkuris** [comment]
Actually, this isn't really true. Please see https://github.com/satori/go.uuid/pull/50

**Comment by jbsturgeon** [comment]
Could the library just return an error if the time isn't valid?  A lot of libraries (including this one) have time based UUID's.  I'm trying to move away from gocql and this is the best alternative minus this one missing function.

**Comment by rkuris** [comment]
@jbsturgeon that's exactly what PR #50 does, unless you're saying that there is some kind of timestamp embedded in a Type 1 UUID that is outside the golang time type's range.

If that's indeed the case, please comment on #50 and provide a sample Type 1 UUID that has an invalid time and doesn't return an error. I'll be happy to amend the PR.
