### ISSUE TITLE
It has any sense NullUUID struct?

### ISSUE THREAD

**Issue by dashaus** [satori/go.uuid#32]
I don't found the explication to NullUUID struct. A array can't be nil, so a NULL value in databases should be a zero value in a array for Go.

I would change the Value method to:

```go
func (u UUID) Value() (driver.Value, error) {
    if u.IsZero() {
         return nil, nil
    }
	return u.String(), nil
}
```

And would remove the NullUUID

**Comment by satori** [comment]
In SQL standard NULL means an **absence of value**, while Nil UUID from RFC states for a **zero value** of UUID. You can find further discussion in #23

**Comment by dashaus** [comment]
Ups! Ok, makes sense. Thanks!
