### ISSUE TITLE
Truncated UUIDs in BINARY(16)

### ISSUE THREAD

**Issue by EmperorEarth** [satori/go.uuid#46]
When using [go-sql-driver's mysql package](https://github.com/go-sql-driver/mysql), occasionally (~1%-3% of the time), the uuid's get clipped when saving to the database. I haven't found a full pattern yet, so I can't be sure it's in your package, go-sql-driver's package, or something else. Here's what I know:

Git hash: b061729afc07e77a8aa4fad0a2fd840958f1942a
MariaDB v10.1.16 on Windows 7x64 (also on Ubuntu 16.04 LTS)
Go 1.8
ID columns are BINARY(16)
UUIDv1
It sometimes truncates two characters, seemingly in the first eight characters (in the `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` form)
The last two characters become `00`

Sample code:
```
import (
	"database/sql"
	"fmt"

	"github.com/satori/go.uuid"
)

func foo(db *sql.DB) {
	id := uuid.NewV1()
	_, _ := db.Exec(fmt.Sprintf("INSERT INTO bar (id, baz) VALUES ('%s', '%s')", id.Bytes(), "baq"))
}
```

In place of fmt.Sprintf, I have a parameter sanitizer.

**Comment by EmperorEarth** [comment]
Some more data (from Ubuntu 16.04 LTS)

Bugged UUIDs are bolded
UUIDs generated within the same transaction are included for context

> **`79CF2018CA11E7A6B67EF825168B4700`**
> `79CFA7B018CA11E7A6B67EF825168B47`
> `79CFE78B18CA11E7A6B67EF825168B47`
> `79CFF7C418CA11E7A6B67EF825168B47`
> `79D0080D18CA11E7A6B67EF825168B47`

> `E73A909E18A811E7A6B67EF825168B47`
> **`E7029918A811E7A6B67EF825168B4700`**
> **`E715FD18A811E7A6B67EF825168B4700`**
> **`E729E518A811E7A6B67EF825168B4700`**
> **`E73A4818A811E7A6B67EF825168B4700`**
> **`E74E7B18A811E7A6B67EF825168B4700`**
> `E75A114718A811E7A6B67EF825168B47`
> `E75A33DD18A811E7A6B67EF825168B47`
> `E75A9FC418A811E7A6B67EF825168B47`
> `E75ACDC618A811E7A6B67EF825168B47`
> `E75AE77118A811E7A6B67EF825168B47`
> `E75AFB8218A811E7A6B67EF825168B47`
> `E75B19E118A811E7A6B67EF825168B47`
> `E75B2D4518A811E7A6B67EF825168B47`
> `E75B3F8818A811E7A6B67EF825168B47`
> `E75B612418A811E7A6B67EF825168B47`
> `E75B739118A811E7A6B67EF825168B47`
> `E75B972218A811E7A6B67EF825168B47`
> `E75BA97618A811E7A6B67EF825168B47`
> `E75BBDAF18A811E7A6B67EF825168B47`
> `E75BCEC618A811E7A6B67EF825168B47`
> `E75BDE3418A811E7A6B67EF825168B47`
> `E75BF29718A811E7A6B67EF825168B47`

> `466CB10218A911E7A6B67EF825168B47`
> `468F336A18A911E7A6B67EF825168B47`
> `468F4A5618A911E7A6B67EF825168B47`
> **`468F8118A911E7A6B67EF825168B4700`**

> `1E000BC118AA11E7A6B67EF825168B47`
> `00C9FCD618AE11E7A6B67EF825168B47`
> **`1E255E18AA11E7A6B67EF825168B4700`**
> `1E25864018AA11E7A6B67EF825168B47`
> `1E25A10318AA11E7A6B67EF825168B47`
> `1E25C0A118AA11E7A6B67EF825168B47`
> `1E25D52418AA11E7A6B67EF825168B47`
> `1E25E67B18AA11E7A6B67EF825168B47`
> `1E2607F718AA11E7A6B67EF825168B47`
> `1E26264918AA11E7A6B67EF825168B47`
> `1E263EFE18AA11E7A6B67EF825168B47`

So far, 12 of my 579 UUIDs have trailing `00`'s (Just over 2%)

**Comment by EmperorEarth** [comment]
Can it be my sanitizer?

```
func sanitizeSQL(format string, args ...interface{}) string {
	for i := range args {
		args[i] = sanitizeArg(args[i])
	}
	return fmt.Sprintf(format, args...)
}
```
```
func sanitizeArg(v interface{}) interface{} {
	s, ok := v.(string)
	if !ok {
		return v
	}

	// protect vs sql injection
	s = strings.Replace(s, "\\", "\\\\", -1)
	s = strings.Replace(s, "\"", "\\\"", -1)
	s = strings.Replace(s, "'", "\\'", -1)

	return strings.TrimSpace(s)
}
```

**Comment by EmperorEarth** [comment]
[Probably solved by methane here](https://github.com/go-sql-driver/mysql/issues/558#issuecomment-292403249)

**Comment by satori** [comment]
@EmperorEarth the problem might be that you are formatting `.Bytes()` output into `%s` instead of `.String()`
