### ISSUE TITLE
is a uuid strip function help?

### ISSUE THREAD

**Issue by zwpaper** [satori/go.uuid#53]
Hi, thanks for the great repo, but when I was using the repo, I found that sometimes I need a strip uuid, like `6ba7b8109dad11d180b400c04fd430c8`, just get rid of `-` in line.

I have to use the `strings` package to replace the `-`, I was thinking if `go.uuid` can provided a `strip` function to make it simple

also, I can write a PR for this, if `go.uuid` like this proposal.

thanks

**Comment by iaroslav-ciupin** [comment]
I find this useful as well. It would be great to have this feature.

**Comment by satori** [comment]
Thanks for using the library, unfortunately I don't see much value in method like that as it should be simple oneliner `hex.EncodeToString(u.Bytes())`.
