### ISSUE TITLE
Is uuid.NewV4() globally unqiue?

### ISSUE THREAD

**Issue by lafreak** [satori/go.uuid#65]
If I use this package in 2 different packages and use these in my go command, will all uuids be unique?
Maybe it sounds like language specific question, I'm still new in Go.

**Comment by n00dl3** [comment]
It's highly improbable, but that does not mean it is impossible. uuid v4 are generated using crypto/rand package, which is supposed to have sufficient entropy.

From wikipedia :

>  In the case of standard version 1 and 2 UUIDs using unique MAC addresses from network cards, collisions can occur only when an implementation varies from the standards, either inadvertently or intentionally.
>In contrast with version 1 and 2 UUIDs using randomly-generated node ids, hash-based version 3 and 5 UUIDs, and random version 4 UUIDs, collisions can occur even without implementation problems, albeit with a probability so small that it can normally be ignored.

**Comment by satori** [comment]
Closing the issue as @n00dl3 provided the correct answer.
