### ISSUE TITLE
not enough arguments in call to uuid.Must

### ISSUE THREAD

**Issue by anks333** [satori/go.uuid#70]
not enough arguments in call to uuid.Must
    have (uuid.UUID)
    want (uuid.UUID, error)

if I install the package using dep `dep ensure -add github.com/satori/go.uuid`, then Must function expects two arguments.

`uuid := uuid.Must(uuid.NewV4(), errors.New("UUID Error"))`

but if I install the package using `go get github.com/satori/go.uuid`, then Must function expects only 1 argument

`uuid := uuid.Must(uuid.NewV4())`

In both the cases 1.2 version is getting installed

**Comment by Sectorbob** [comment]
I am experiencing the same sort of behavior. `go get -u` places the correct revision (I assume), while `dep init` or `dep ensure` are causing the `vendor/` contents to act awry.

**Comment by skmgw** [comment]
I have faced the same issue.
The change ( https://github.com/satori/go.uuid/issues/66 ) cause this issue is assumed.

~~~~
$ go get -u github.com/osrg/gobgp/gobgpd
# github.com/osrg/gobgp/table
go/src/github.com/osrg/gobgp/table/path.go:392: multiple-value uuid.NewV4() in single-value context
~~~~

**Comment by macrael** [comment]
See #66

**Comment by thurt** [comment]
@anks333 i think you would get this error only if you are using the api from master but have 1.2 installed in vendor/

> If anybody is coming here from Googling build errors and you're using dep then you'll need to change your Gopkg.toml to point to the master branch for go.uuid.
> 
> Like so:
> 
> [[override]]
>   name = "github.com/satori/go.uuid"
>   revision = "master"

**Comment by klj890** [comment]
I have a similar question.
I used go version 1.11.
When I use **module** , it will be prompted as follows:
```
➜ :  GO111MODULE=on go run app.go
# portal-for-gdt/model
model/uias.go:42:23: not enough arguments in call to uuid.Must
	have (uuid.UUID)
	want (uuid.UUID, error)
```
but, if set ``` GO111MODULE=off ``` , All is well。。。。
this is my code:
```
acc.State = uuid.Must(uuid.NewV4()).String()
```

**Comment by ai0376** [comment]
```
$ go mod edit -replace=github.com/satori/go.uuid@v1.2.0=github.com/satori/go.uuid@master
$ go mod tidy
$ go build
```
It's will ok! @anks333

**Comment by jdharms** [comment]
@mjrao Thank you so much!

**Comment by hubyhuby** [comment]
I tried several of the options in this thread, but none worked for me on go 1.12.
I finally switch to github.com/gofrs/uuid and it worked instantaneously ! Even with GO111MODULE=on

**Comment by bheemreddy181-zz** [comment]
go get github.com/satori/go.uuid@master will work

**Comment by griffincox** [comment]
Thanks Bheem @bheemreddy181

**Comment by ShrawanLakhe** [comment]
Thanks @bheemreddy181

**Comment by mengdodo** [comment]
Thanks @bheemreddy181

**Comment by ghost** [comment]
Thanks @bheemreddy181

**Comment by LBiff** [comment]
> go get github.com/satori/go.uuid@master will work

Thanks, good job!! But why it can be work?
---------------------------------------------------------------------------------------
“github.com/koding/kite” ==> this project also refers to the "master"  with dep:

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"
-------------------------------------------------------------------------------------
But that does not work with the follow error when i import it (github.com/koding/kite) directly to my own project.

not enough arguments in call to uuid.Must
have (uuid.UUID)
want (uuid.UUID, error)

------------------------------------------------------------------------------------
But it can work when i  command "go get xxx.uuid@master" or add "xxx.uuid master" to go.mod.

so, why?  Hasn't this project been refered to master? why we need get the master branch agin?
