### ISSUE TITLE
Any potential problems for changing Size from 16 to 8

### ISSUE THREAD

**Issue by vonzcy** [satori/go.uuid#78]
I need 64-bit uuids, so I wish to change Size to 8. Any potential problems? I am mainly using Version4.

**Comment by theckman** [comment]
@vonzcy yes, it would cause issues because UUIDs need 128 bits per RFC-4122. Because there are 8 bits to a byte, changing this to `8` would only allow us to store 64 bits worth of data. Whereas a size of 16 leads to 128 bits.

- https://tools.ietf.org/html/rfc4122#section-4.1.2
