### ISSUE TITLE
fork with tag v2.0.0, state = current master

### ISSUE THREAD

**Issue by monkeydioude** [satori/go.uuid#80]
I forked satori's repo and made a [v2.0.0 tag using the current master](https://github.com/monkeydioude/go.uuid/releases/tag/v2.0.0) of the project while waiting for any activity from @satori .

Hope this helps.

edit: I rather created a v2.0.0 tag since changes in this version are breaking

**Comment by theckman** [comment]
Some members of the Go community have come together to adopt this package. We did a v2.0.0 release today:

- https://github.com/gofrs/uuid
