### ISSUE TITLE
Is uuid.NewV4() thread safe?

### ISSUE THREAD

**Issue by thanhps42** [satori/go.uuid#81]
When I call uuid.NewV4() in multiple goroutine, I have some question:
- thread-safe?
- Can I get same uuid when multiple goroutine call it at same time?
P/s: sorry for my bad English

Thanks.

**Comment by metaleap** [comment]
Globals and thread-safety are only of concern if there are writes happening to the global (or more specifically, to some piece of _shared_ data, globally-scoped-or-not) concurrently with reads. Not seeing this here, a never-EOF'ing read-only rand reader is pretty safe to begin with. What sort of state might it have to protect, really? _But_ to top it off, for the linux/unix/bsd/plan9 impl there _is_ seemingly a mutex on the underlying `/dev/rand` Reader anyway! see https://golang.org/src/crypto/rand/rand_unix.go
