### ISSUE TITLE
Issue using go.uuid in docker container

### ISSUE THREAD

**Issue by zachlefevre** [satori/go.uuid#88]
This line: ```aggregateID, _ := uuid.NewV4()``` works perfectly  when building on my machine, but I receive the error ```./main.go:51:17: assignment mismatch: 2 variables but 1 values``` when building with the following docker image:
```
FROM golang:latest as builder
WORKDIR /go/src/github.com/zachlefevre/project_hopper_backend/algorithmAPI
COPY . .
RUN go get -u github.com/golang/dep/cmd/dep
RUN dep init && dep ensure
```

Any help would be greatly appreciated.

**Comment by mdanzinger** [comment]
Offhand it sounds like this may be an issue with dep getting an older version of satori. You may want to open an issue with dep. Migrating over to Go's modules might also solve this.

**Comment by ghost** [comment]
https://github.com/satori/go.uuid/issues/84 Does this happen with the drop in replacement from https://github.com/gofrs/uuid ?

**Comment by zachlefevre** [comment]
@DamareYoh It does not. The API is the same across my local instance and docker.
