### ISSUE TITLE
error value when doing rand.Read(...)

### ISSUE THREAD

**Issue by cyx** [satori/go.uuid#9]
First of all thanks for a great library.

This is more of a question rather than a real issue: what happens if rand.Read() fails? I realize in practice it probably doesn't fail much (and I've been running a script locally to try and catch a random failure for crypt.Rand() but haven't had any luck) -- but in that rare case what should be the behavior of the library?

Maybe a retry works? If so I'll be happy to do a PR.

**Comment by satori** [comment]
Currently if `rand.Read` fails, `NewV4` will return partially malformed UUID. I believe it wouldn't be random at all, but still will have version and variants bits set properly.

Retry wouldn't help always, for example, try to `chmod -r /dev/urandom` locally.
There are sometimes errors you can't handle, so in this case it would be correct to just return error from `NewV4`.

It leads to another problem: library interface should be changed that definitely will break backwards compatibility.

**Comment by cbandy** [comment]
We read also in `init()`. I'm not sure of the correct way to handle errors here.

**Comment by cbandy** [comment]
There are a few [open issues related to this topic](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+crypto%2Frand+in%3Atitle), notably \#7940 and \#9205.

**Comment by cyx** [comment]
Possibly one solution is to just issue a panic here, since this errors from /dev/random is more of an outlier that it probably warrants a panic.

They do the same fwiw: https://github.com/hashicorp/raft/blob/master/util.go#L43

**Comment by satori** [comment]
@cyx I agree with your point and will be happy to merge such PR
There is still a `rand.Read` inside of `init` as mentioned by @cbandy, is it safe to `panic` there as well?

**Comment by cyx** [comment]
I think it's safe to panic there as well, init context means typically the
web app's startup process. I doubt you'd want to start up your app on a
server with a failing /dev/random.

Thoughts?
